server:
  port: 8085
  context-path: /cmfz
  jsp-servlet:
    init-parameters:
      development: true
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/chiming
    username: root
    password: 123456
  mvc:
    view:
      prefix: /
      suffix: .jsp
  http:
    encoding:
      force: true
      charset: UTF-8
    multipart:
      max-file-size: 20MB
      max-request-size: 200MB
mybatis:
  type-aliases-package: com.baizhi.entity